### ISSUE TITLE
User object

### ISSUE THREAD

**Issue by VanJackal** [InternetEnemies/combatcritters-ts#12]
- [x] User cards object
- [x] user cards.getCards

**Comment by whatdoes3plus1equalsto** [comment]
these two tasks are done?

**Comment by VanJackal** [comment]
> these two tasks are done?

not as far as I know

**Comment by whatdoes3plus1equalsto** [comment]
Is this task supposed to complete UserCardsManager?

> > these two tasks are done?
> 
> not as far as I know

**Comment by VanJackal** [comment]
This task is for finishing the concrete implementation of IUser, which will use UserCardsManager. so yes

**Comment by whatdoes3plus1equalsto** [comment]
got it, thanks

**Comment by whatdoes3plus1equalsto** [comment]
this issue could be closed as well since its functionalities have be merged
