### ISSUE TITLE
OffersManager

### ISSUE THREAD

**Issue by whatdoes3plus1equalsto** [InternetEnemies/combatcritters-ts#60]
- [ ] getDiscounts
- [ ] getSpecials
- [ ] getOffers

**Comment by whatdoes3plus1equalsto** [comment]
@VanJackal @kivine99  Is this manager necessary at this point if we moving it to vendor field #75 ? Since we already have getOffers(), discountOffers(), getSpecialOffers() in vendor field.

**Comment by whatdoes3plus1equalsto** [comment]
> @VanJackal @kivine99 Is this manager necessary at this point if we moving it to vendor field #75 ? Since we already have getOffers(), discountOffers(), getSpecialOffers() in vendor field.

Or should this be the wrapper for these three functions?

**Comment by VanJackal** [comment]
If those methods are on vendor instead then OffersManager isn't needed
